name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: install
      run: sudo apt-get install libboost-system-dev libboost-test-dev libboost-thread-dev libqwt-qt5-dev qtbase5-dev
     
    - name: build
      run: mkdir build
     
    - name: current direc
      run: cd build
     
    - name: cmake 
      run: cmake ../
 
    - name: make
      run: | 
        make
               
 
